# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

odds_no_sharing <- function(kappa, p, ndis) {
    .Call(`_flashfmZero_odds_no_sharing`, kappa, p, ndis)
}

concat <- function(x) {
    .Call(`_flashfmZero_concat`, x)
}

calcDij <- function(i, j, Cr12, Vr1, Vr2) {
    .Call(`_flashfmZero_calcDij`, i, j, Cr12, Vr1, Vr2)
}

pairs <- function(M) {
    .Call(`_flashfmZero_pairs`, M)
}

indices <- function(M) {
    .Call(`_flashfmZero_indices`, M)
}

Mlogsum1 <- function(x) {
    .Call(`_flashfmZero_Mlogsum1`, x)
}

Mlogsum <- function(x) {
    .Call(`_flashfmZero_Mlogsum`, x)
}

calcDelta <- function(imods, N, M, dcon, Vr, Cr, c2) {
    .Call(`_flashfmZero_calcDelta`, imods, N, M, dcon, Vr, Cr, c2)
}

calcQD3 <- function(mod1, N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, c2, lPP, Nsame) {
    .Call(`_flashfmZero_calcQD3`, mod1, N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, c2, lPP, Nsame)
}

ppadjT3 <- function(N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, c2, lPP, Nsame) {
    .Call(`_flashfmZero_ppadjT3`, N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, c2, lPP, Nsame)
}

calcQD4 <- function(mod1, N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, Nq3, Ldcon123, Cr3, lPP, Nsame) {
    .Call(`_flashfmZero_calcQD4`, mod1, N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, Nq3, Ldcon123, Cr3, lPP, Nsame)
}

ppadjT4 <- function(N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, Nq3, Ldcon123, Cr3, lPP, Nsame) {
    .Call(`_flashfmZero_ppadjT4`, N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, Nq3, Ldcon123, Cr3, lPP, Nsame)
}

calcQD5 <- function(mod1, N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, Nq3, Ldcon123, Cr3, Nq4, Ldcon1234, Cr4, lPP, Nsame) {
    .Call(`_flashfmZero_calcQD5`, mod1, N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, Nq3, Ldcon123, Cr3, Nq4, Ldcon1234, Cr4, lPP, Nsame)
}

ppadjT5 <- function(N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, Nq3, Ldcon123, Cr3, Nq4, Ldcon1234, Cr4, lPP, Nsame) {
    .Call(`_flashfmZero_ppadjT5`, N, nummods, Vr, Cr, dcon, keep, Nqq, Ldcon12, Nq3, Ldcon123, Cr3, Nq4, Ldcon1234, Cr4, lPP, Nsame)
}

calcQD6fast <- function(mod1, N, nummods, Vr, Cr, dcon, keep, lPP) {
    .Call(`_flashfmZero_calcQD6fast`, mod1, N, nummods, Vr, Cr, dcon, keep, lPP)
}

ppadjT6fast <- function(N, nummods, Vr, Cr, dcon, keep, lPP) {
    .Call(`_flashfmZero_ppadjT6fast`, N, nummods, Vr, Cr, dcon, keep, lPP)
}

